# Generated by Django 2.2 on 2021-02-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=240)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.PositiveIntegerField()),
                ('branch', models.CharField(choices=[('KTM', 'Kathmandu'), ('BKT', 'Bhaktapur'), ('LTP', 'Lalitpur')], max_length=25)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
