# Generated by Django 2.2 on 2021-02-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='message_query',
        ),
    ]
